EnrollTrack/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include  # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static  # type: ignore
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path # type: ignore
from . import views

urlpatterns = [
    path('home/', views.home_page, name = "home" ),
    path('about/', views.about_page, name = "about" ),
    path('contact/', views.contact_page, name = "contact" ),
    path('login/', views.login_page, name = "login" ),
    path('crud/', views.crud_page, name = "crud" ),
    
]

webapp/models.py
from django.db import models # type: ignore

class Program(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=50, null=True)
    age = models.IntegerField()
    phone = models.CharField(max_length=20)  
    email = models.EmailField(max_length=50, blank=True)
    program = models.ForeignKey(Program, on_delete=models.CASCADE, related_name='students', blank=True, null=True)

    @property
    def enrolled_course(self):
        try:
            enrollment = self.enrollments.first()
            if enrollment:
                return enrollment.course
        except Enrollment.DoesNotExist:
            pass
        return None

    def __str__(self):
        return self.name

class Teacher(models.Model):
    name = models.CharField(max_length=50)
    specialization = models.CharField(max_length=100)
    courses_taught = models.ForeignKey(Program, on_delete=models.CASCADE, related_name='teachers_taught', blank=True, null=True)

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=100)
    program = models.ForeignKey(Program, on_delete=models.CASCADE, related_name='courses')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='courses_taught_by_teacher')

    def __str__(self):
        return self.name

class Enrollment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='enrollments')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments')

    def __str__(self):
        return f"{self.student.name} enrolled in {self.course.name}"

webapp/forms.py
from django import forms # type: ignore
from django.forms import ModelForm # type: ignore
from .models import Program, Course

class LoginForm(forms.Form):
    name = forms.CharField(label='Full Name', max_length=100)
    age = forms.IntegerField(label='Age')
    phone = forms.CharField(label='Contact Number', max_length=20)
    email = forms.EmailField(label='Email')
    program = forms.ModelChoiceField(queryset=Program.objects.all(), empty_label='Select Program')
    course = forms.ModelChoiceField(queryset=Course.objects.all(), empty_label='Select Course')

webapp/views.py
from django.shortcuts import render, redirect # type: ignore
from django.http import HttpResponse # type: ignore
from .models import *
from .forms import LoginForm
from django.shortcuts import get_object_or_404, redirect # type: ignore

def home_page(request):
    return render(request,'pages/home.html')

def about_page(request):
    return render(request,'pages/about.html')

def contact_page(request):
    return render(request,'pages/contact.html')

def login_page(request):
    programs = Program.objects.all()
    courses = Course.objects.all()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # Extract data from validated form
            full_name = form.cleaned_data['name']
            age = form.cleaned_data['age']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            program_id = form.cleaned_data['program'].id
            course_id = form.cleaned_data['course'].id

            try:
                # Create a new Student instance
                student = Student.objects.create(
                    name=full_name,
                    age=age,
                    phone=phone,
                    email=email,
                    program_id=program_id  
                )

                # Create a new Enrollment instance
                enrollment = Enrollment.objects.create(
                    student=student,
                    course_id=course_id  
                )

                # Clear the form after successful submission
                form = LoginForm()

                # Redirect to CRUD page after successful submission
                return redirect('crud_page')

            except Exception as e:
                print(e) 
    else:
        form = LoginForm()

    return render(request, 'pages/loginform.html', {'form': form, 'programs': programs, 'courses': courses})

def crud_page(request):
    if request.method == 'POST':
        # Check if the form is for deleting a student
        if 'delete_student' in request.POST:
            student_id = request.POST.get('delete_student')
            student = get_object_or_404(Student, id=student_id)
            student.delete()
            return redirect('crud_page')

    students = Student.objects.prefetch_related('program').all()
    return render(request, 'pages/crud.html', {'students': students})

webapp/templates/pages/about.html
{% load static %}
<title>About Us</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% include 'pages/navbar.html' %}

<img src="{% static 'images/check.png' %}" alt="" class="aboutImage">

<div class="aboutContainer">  
    <div class="aboutInfo">
        <h1 class="aboutheader">About Us:</h1><br>
        <p>Our enrollment tracking system is a software tool we use to manage student enrollment. It helps with registration, course selection, tracking enrollment status, advising, and reporting. It makes our enrollment process smoother, improves communication, and provides useful data for planning.</p>
    </div>
</div>

<script src="{% static 'js/script.js' %}"></script>

webapp/templates/pages/contact.html
{% load static %}
<title>Contact Us</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<body class="cform">
{% include 'pages/navbar.html' %}

<div class="conContainer">
    <form class="conForm">
        <h1>Contact Form</h1>
        <ul>
            <li>
                <label for="name"><span>Name <span class="required-star">*</span></span></label>
                <input type="text" id="name" name="user_name">
            </li>
            <li>
                <label for="mail"><span>Email <span class="required-star">*</span></span></label>
                <input type="email" id="mail" name="user_email">
            </li>
            <li>
                <label for="msg"><span>Message</span></label>
                <textarea id="msg" rows="4" cols="50" name="user_message"></textarea>
            </li>
            <li>
                <input type="submit" value="Submit">
            </li>
        </ul>
    </form>
</div>

<script src="{% static 'js/script.js' %}"></script>
</body>

webapp/templates/pages/crud.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crud Table</title>
    <link rel="stylesheet" href="{% static 'css/crud.css' %}">
</head>
<body>
    <h2>Enroll Track</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Age</th>
                <th>Phone</th>
                <th>Program</th>
                <th>Courses</th>
                <th>Teacher</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr id="student-{{ student.id }}">
                <td>{{ student.name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.phone }}</td>
                <td>{{ student.program }}</td>
                <td>
                    <ul>
                        {% for enrollment in student.enrollments.all %}
                        <li>{{ enrollment.course.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for enrollment in student.enrollments.all %}
                        <li>{{ enrollment.course.teacher.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a href="#" class="edit-btn">Edit</a>
                    <a href="#" class="delete-btn">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- The Modal -->
    <div id="editModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Edit User</h3>
            <div class="form-container">
                <form id="editUserForm">
                    <input type="hidden" id="editRowIndex" value="">
                    <label for="editName">Name:</label>
                    <input type="text" id="editName" name="editName" required>
                    <label for="editEmail">Email:</label>
                    <input type="email" id="editEmail" name="editEmail" required>
                    <label for="editAge">Age:</label>
                    <input type="text" id="editAge" name="editAge" required>
                    <label for="editPhone">Phone:</label>
                    <input type="text" id="editPhone" name="editPhone" required>
                    <label for="editProgram">Program:</label>
                    <select id="editProgram" name="editProgram">
                        {% for program in programs %}
                        <option value="{{ program.id }}">{{ program.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="editCourses">Courses:</label>
                    <select id="editCourses" name="editCourses">
                        {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="editTeacher">Teacher:</label>
                    <select id="editTeacher" name="editTeacher">
                        {% for teacher in teachers %}
                        <option value="{{ teacher.id }}">{{ teacher.name }}</option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Save">
                </form>
            </div>
        </div>
    </div>

    <script src="{% static 'js/crud.js' %}"></script>

webapp/templates/pages/home.html
{% extends 'pages/index.html' %}

{% block content %}
{% include 'pages/navbar.html' %}
<main>
    <section class="header container">
        <div>
            <h1 class="home_header">"Empowering minds through education."</h1>

            <img src="../static/images/book.png" alt="">
            <div>
                <a href="{% url 'login' %}"><button class="btn">Enroll Now!</button></a>
            </div>
        </div>
    </section>
</main>

{% for abc in students %}
{{abc.name}}
{% endfor %} 

{% endblock %}

webapp/templates/pages/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enroll Track</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="../static/images/CG.png">   
</head>
<body>
    
    {% block content %}

    {% include 'pages/navbar.html' %}

    {% endblock %}
   
    <script src="{% static '/js/script.js' %}"></script>
</body>
</html>

webapp/templates/pages/loginform.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Enrollment Form</title>
  <link rel="stylesheet" href="{% static 'css/loginform.css' %}">
  <link rel="icon" type="image/x-icon" href="{% static 'images/CG.png' %}">
</head>

<body class="loginbody">
  {% include 'pages/navbar.html' %}
  <div id="event-registration">

      <form id="event-registration-form" method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        <fieldset class="loginformFieldset">
          <h3>Personal Information</h3>
          <label for="id_name">Full Name</label>
          {{ form.name }}
          <label for="id_age">Age</label>
          {{ form.age }}
          <label for="id_phone">Contact Number</label>
          {{ form.phone }}
          <label for="id_email">Email</label>
          {{ form.email }}

          <!-- Program Selection -->
          <label for="id_program">Program</label>
          {{ form.program }}

          <!-- Course Selection -->
          <label for="id_course">Course</label>
          {{ form.course }}
        </fieldset>
        <button type="submit" class="loginbuttons">Submit Form</button>
      </form>

    </div> 
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

webapp/templates/pages/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="icon" type="image/x-icon" href="../static/images/CG.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
 
<body class="mobile">
    <nav class="nav-bar">
        <div class="container nav-wrapper">
            <div class="brand">
                <img src="../static/images/CG.png" alt="" class="logo=img">
                <span><strong>ENROLL TRACK</strong></span>
            </div>
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <ul class="nav-list">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>               
                <li><a href="{% url 'contact' %}">Contact</a></li>
                <li>
                <a href="{% url 'login' %}"><button class="btn">Enroll</button></a>
                </li>
                <li>
                <a href="{% url 'crud' %}"><i class='far fa-user-circle' style='font-size:24px'></i></a>
                </li>
            </ul>
        </div>
    </nav>   
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</body>